config/routes.rb
Rails.application.routes.draw do
  resources :pictures

  root 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Your photo was added!' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Thanks for the update!' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'DESTRUCTION!!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picture Perfect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<div class="form"  
  <%= form_for(@picture) do |f| %>
    <% if @picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

        <ul>
        <% @picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :url %><br>
      <%= f.text_field :url %>
    </div>
    <div class="actions">
      <%= f.submit "Upload Photo"%>
    </div>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<div class="main">

<h2>Update a photo...</h2>

<%= render 'form' %>

<%= link_to 'view', @picture %> |
<%= link_to '<< go back', pictures_path %>

</div>

app/views/pictures/index.html.erb
<header>
<h1>Picture Perfect!</h1>
<h4>a simple photo gallery for friends...and frenemies...</h4>
<nav>
<%= link_to '+ add a photo!', new_picture_path %>
</nav>
</header>
<!-- <p id="notice"><%= notice %></p> -->

  <main>
    <div class="main">
      <% @pictures.each do |picture| %>
        <span class="title"><%= link_to picture.title, picture %></span>
        <br>
        <span class="photo"><%= image_tag picture.url %></span>
          <ul class=todo>
            <li><%= link_to 'view', picture %></li>
            <li><%= link_to 'edit', edit_picture_path(picture) %></li>
            <li><%= link_to 'delete', picture, method: :delete, data: { confirm: 'You sure about that??' } %></li>
          </ul>
      <% end %>
    </div>
  </main>

<br>

app/views/pictures/new.html.erb
<div class="main">

<h2>Add a new photo...</h2>

<%= render 'form' %>

<%= link_to '<< go back', pictures_path %>

</div>

app/views/pictures/show.html.erb
<div class="main">

<p id="notice"><%= notice %></p>

<h2>
  <strong><%= @picture.title %></strong>
</h2>

<p>
  <%= image_tag @picture.url %>
</p>

<%= link_to 'edit', edit_picture_path(@picture) %> |
<%= link_to '<< go back', pictures_path %>

</div>